[build]
target = "index.html"
dist = "../dist"

[serve]
port = 3443

[[proxy]]
backend = "http://localhost:8080/api/"
insecure = true

[[proxy]]
backend = "http://localhost:8080/auth/token"
insecure = true
